[31m[E 201223 00:40:36 mm_builder:89][39m Could not open json file: template-vap_corp.json
    Traceback (most recent call last):
      File "/home/hkefi/Workspace/script/template_builder/mm_builder.py", line 75, in __init__
        open(self.__vap_corp_filename, 'r') as f_vap_corp,\
    FileNotFoundError: [Errno 2] No such file or directory: 'template-vap_corp.json'
[31m[E 201223 00:40:38 mm_builder:89][39m Could not open json file: template-vap_corp.json
    Traceback (most recent call last):
      File "/home/hkefi/Workspace/script/template_builder/mm_builder.py", line 75, in __init__
        open(self.__vap_corp_filename, 'r') as f_vap_corp,\
    FileNotFoundError: [Errno 2] No such file or directory: 'template-vap_corp.json'
[31m[E 201223 00:42:47 mm_builder:89][39m Could not open json file: template-vap_corp.json
    Traceback (most recent call last):
      File "/home/hkefi/Workspace/script/template_builder/mm_builder.py", line 75, in __init__
        open(self.__vap_corp_filename, 'r') as f_vap_corp,\
    FileNotFoundError: [Errno 2] No such file or directory: 'template-vap_corp.json'
[31m[E 201223 00:42:48 mm_builder:89][39m Could not open json file: template-vap_corp.json
    Traceback (most recent call last):
      File "/home/hkefi/Workspace/script/template_builder/mm_builder.py", line 75, in __init__
        open(self.__vap_corp_filename, 'r') as f_vap_corp,\
    FileNotFoundError: [Errno 2] No such file or directory: 'template-vap_corp.json'
[31m[E 201223 00:44:48 mm_builder:89][39m Could not open json file: template-vap_corp.json
    Traceback (most recent call last):
      File "/home/hkefi/Workspace/script/template_builder/mm_builder.py", line 75, in __init__
        open(self.__vap_corp_filename, 'r') as f_vap_corp,\
    FileNotFoundError: [Errno 2] No such file or directory: 'template-vap_corp.json'
[31m[E 201225 01:53:01 mm_builder:156][39m Could not open json file: tamplate-aaa-radius.json
    Traceback (most recent call last):
      File "/home/hkefi/Workspace/script/template_builder/mm_builder.py", line 131, in __init__
        open(self.__aaa_radius_filename, 'r') as f_radius,
    FileNotFoundError: [Errno 2] No such file or directory: 'tamplate-aaa-radius.json'
